# Generated by Django 3.1.1 on 2020-12-14 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArmedGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('deads', models.IntegerField()),
            ],
            options={
                'db_table': 'armed_groups',
            },
        ),
        migrations.CreateModel(
            name='Conflict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sort', models.CharField(max_length=100)),
                ('wounded', models.IntegerField()),
                ('deads', models.IntegerField()),
            ],
            options={
                'db_table': 'conflicts',
            },
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'dealers',
            },
        ),
        migrations.CreateModel(
            name='MilitaryChief',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=100)),
                ('division_number', models.IntegerField()),
                ('armed_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.armedgroup')),
            ],
            options={
                'db_table': 'military_chiefs',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sort', models.CharField(max_length=100)),
                ('amount_people', models.IntegerField()),
                ('sort_of_help', models.CharField(max_length=100)),
                ('leader', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='PoliticalLeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('support', models.CharField(max_length=100)),
                ('armed_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.armedgroup')),
            ],
            options={
                'db_table': 'politcal_leaders',
                'unique_together': {('id', 'armed_group')},
            },
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('indicator', models.IntegerField()),
            ],
            options={
                'db_table': 'weapons',
            },
        ),
        migrations.CreateModel(
            name='SupplyWeaponArmedGroupDealer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapons_amount', models.IntegerField()),
                ('armed_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.armedgroup')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dealer')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.weapon')),
            ],
            options={
                'db_table': 'supply_weapons_armed_groups_dealers',
            },
        ),
        migrations.CreateModel(
            name='PoliticalLeadersMilitaryChiefs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('military_chief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.militarychief')),
                ('political_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.politicalleader')),
            ],
            options={
                'db_table': 'political_leaders_military_chiefs',
            },
        ),
        migrations.AddField(
            model_name='militarychief',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.politicalleader'),
        ),
        migrations.CreateModel(
            name='Religious',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.conflict')),
            ],
            options={
                'db_table': 'religious_wars',
                'unique_together': {('id', 'conflict')},
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.conflict')),
            ],
            options={
                'db_table': 'region_wars',
                'unique_together': {('id', 'conflict')},
            },
        ),
        migrations.CreateModel(
            name='ExitPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exit_date', models.DateField()),
                ('armed_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.armedgroup')),
                ('conflict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.conflict')),
            ],
            options={
                'db_table': 'exit_part',
                'unique_together': {('armed_group', 'conflict', 'exit_date')},
            },
        ),
        migrations.CreateModel(
            name='ExitMed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exit_date', models.DateField()),
                ('conflict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.conflict')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.armedgroup')),
            ],
            options={
                'db_table': 'exit_med',
                'unique_together': {('organization', 'conflict', 'exit_date')},
            },
        ),
        migrations.CreateModel(
            name='Etnic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.conflict')),
            ],
            options={
                'db_table': 'etnic_wars',
                'unique_together': {('id', 'conflict')},
            },
        ),
        migrations.CreateModel(
            name='EnterPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_date', models.DateField()),
                ('armed_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.armedgroup')),
                ('conflict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.conflict')),
            ],
            options={
                'db_table': 'enter_part',
                'unique_together': {('armed_group', 'conflict', 'enter_date')},
            },
        ),
        migrations.CreateModel(
            name='EnterMed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_date', models.DateField()),
                ('conflict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.conflict')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.armedgroup')),
            ],
            options={
                'db_table': 'enter_med',
                'unique_together': {('organization', 'conflict', 'enter_date')},
            },
        ),
        migrations.CreateModel(
            name='Economic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.conflict')),
            ],
            options={
                'db_table': 'economic_wars',
                'unique_together': {('id', 'conflict')},
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deads', models.IntegerField()),
                ('boats', models.IntegerField()),
                ('tanks', models.IntegerField()),
                ('planes', models.IntegerField()),
                ('mens', models.IntegerField()),
                ('armed_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.armedgroup')),
            ],
            options={
                'db_table': 'divisions',
                'unique_together': {('id', 'armed_group')},
            },
        ),
        migrations.CreateModel(
            name='DialogPoliticalLeaderArmedGroupOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('armed_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.armedgroup')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
                ('political_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.politicalleader')),
            ],
            options={
                'db_table': 'dialog_political_leaders_armed_groups_organizations',
                'unique_together': {('political_leader', 'armed_group', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.conflict')),
            ],
            options={
                'db_table': 'country_wars',
                'unique_together': {('id', 'conflict')},
            },
        ),
        migrations.CreateModel(
            name='CanSupply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_weapons', models.IntegerField()),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dealer')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.weapon')),
            ],
            options={
                'db_table': 'can_supply',
                'unique_together': {('weapon', 'dealer')},
            },
        ),
    ]
